### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by marklove5102** [sboulema/Linky#4]
`````
root@7c50892df46a:/Linky# npm install  --registry=https://registry.npmmirror.com
npm WARN deprecated fontawesome-iconpicker@3.2.0: WARNING: This project has been discontinued.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/",service="npm.fontawesome.com"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-01-29T07_47_42_845Z-debug.log

root@7c50892df46a:/Linky# node -v
v8.17.0



root@f05b90cf96f3:/Linky# npm install
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/",service="npm.fontawesome.com"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-01-29T07_49_31_028Z-debug.log

root@f05b90cf96f3:/Linky# node -v
v14.21.3




root@036dcbbf68ee:/Linky# npm install  --registry=https://registry.npmmirror.com
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN old lockfile HttpErrorAuthUnknown: Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/",service="npm.fontawesome.com"
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:80:17
npm WARN old lockfile     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm WARN old lockfile     at async RegistryFetcher.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:87:19)
npm WARN old lockfile     at async RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:23)
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:727:24)
npm WARN old lockfile  Could not fetch metadata for @fortawesome/fontawesome-pro@5.6.3 HttpErrorAuthUnknown: Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/",service="npm.fontawesome.com"
npm WARN old lockfile     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:80:17
npm WARN old lockfile     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm WARN old lockfile     at async RegistryFetcher.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:87:19)
npm WARN old lockfile     at async RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:23)
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:727:24) {
npm WARN old lockfile   headers: [Object: null prototype] {
npm WARN old lockfile     'content-type': [ 'application/json' ],
npm WARN old lockfile     'content-length': [ '49' ],
npm WARN old lockfile     connection: [ 'keep-alive' ],
npm WARN old lockfile     date: [ 'Mon, 29 Jan 2024 07:50:04 GMT' ],
npm WARN old lockfile     'www-authenticate': [
npm WARN old lockfile       'Basic realm="https://npm.fontawesome.com/",service="npm.fontawesome.com"'
npm WARN old lockfile     ],
npm WARN old lockfile     allow: [ 'GET, PUT, HEAD, OPTIONS' ],
npm WARN old lockfile     'cache-control': [ 'max-age=30, must-revalidate' ],
npm WARN old lockfile     vary: [ 'Cookie' ],
npm WARN old lockfile     'referrer-policy': [ 'same-origin, no-referrer-when-downgrade' ],
npm WARN old lockfile     server: [ 'Cloudsmith MCP' ],
npm WARN old lockfile     'x-frame-options': [ 'DENY' ],
npm WARN old lockfile     'x-content-type-options': [ 'nosniff' ],
npm WARN old lockfile     'x-xss-protection': [ '0' ],
npm WARN old lockfile     'public-key-pins': [
npm WARN old lockfile       'pin-sha256="++MBgDH5WGvL9Bcn5Be30cRcL0f5O+NyoXuWtQdX1aI="; pin-sha256="klO23nT2ehFDXCfx3eHTDRESMz3asj1muO+4aIdjiuY="; pin-sha256="tFOU95aPSUFNfZLpf6OdBnVvAFKxd8zxp4jCbaL3MJ0="; max-age=86400; report-uri="https://cloudsmith.report-uri.io/r/default/hpkp/enforce"'
npm WARN old lockfile     ],
npm WARN old lockfile     'strict-transport-security': [ 'max-age=31536000; includeSubdomains;' ],
npm WARN old lockfile     'expect-ct': [
npm WARN old lockfile       'enforce, max-age=86400, report-uri="https://cloudsmith.report-uri.io/r/default/ct/enforce"'
npm WARN old lockfile     ],
npm WARN old lockfile     'x-cache': [ 'Error from cloudfront' ],
npm WARN old lockfile     via: [
npm WARN old lockfile       '1.1 e67bc999d3ae69aeca2e64717fe718be.cloudfront.net (CloudFront)'
npm WARN old lockfile     ],
npm WARN old lockfile     'x-amz-cf-pop': [ 'ICN51-C1' ],
npm WARN old lockfile     'alt-svc': [ 'h3=":443"; ma=86400' ],
npm WARN old lockfile     'x-amz-cf-id': [ 'KzckMNfEIRwRLJshvbC8vRjsve0zwsWo_9DvoLRYKzrM-G_geRSICA==' ],
npm WARN old lockfile     'x-fetch-attempts': [ '1' ],
npm WARN old lockfile     'x-local-cache-status': [ 'skip' ]
npm WARN old lockfile   },
npm WARN old lockfile   statusCode: 401,
npm WARN old lockfile   code: 'E401',
npm WARN old lockfile   method: 'GET',
npm WARN old lockfile   uri: 'https://npm.fontawesome.com/@fortawesome%2ffontawesome-pro',
npm WARN old lockfile   body: { ok: false, error: 'authentication required' },
npm WARN old lockfile   pkgid: '@fortawesome/fontawesome-pro@5.6.3'
npm WARN old lockfile }
npm WARN old lockfile Error: Integrity checksum failed when using sha512: wanted sha512-z8H8/diyk76B7q5wg+Ud0+CqzcAF3mBBI/bA5ne5zrRUUIvNkJY//D3BqyH571KuAC4Nr7Rw7CjWX4r0y9DvNg== but got sha512-+ux3lx6peh0BpvY0JebGyZoiR4D+oYzdPZMKJwkZ+sFkNJzpL7tXc/wehS49gUAxg3tmMHPHZkA8JU2rhhgDHw==.
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:146:35)
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:727:24)
npm WARN old lockfile  Could not fetch metadata for fsevents@1.2.4 Error: Integrity checksum failed when using sha512: wanted sha512-z8H8/diyk76B7q5wg+Ud0+CqzcAF3mBBI/bA5ne5zrRUUIvNkJY//D3BqyH571KuAC4Nr7Rw7CjWX4r0y9DvNg== but got sha512-+ux3lx6peh0BpvY0JebGyZoiR4D+oYzdPZMKJwkZ+sFkNJzpL7tXc/wehS49gUAxg3tmMHPHZkA8JU2rhhgDHw==.
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:146:35)
npm WARN old lockfile     at async Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:727:24) {
npm WARN old lockfile   code: 'EINTEGRITY'
npm WARN old lockfile }
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR! 
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-01-29T07_50_02_656Z-debug-0.log


root@036dcbbf68ee:/Linky# node -v
v18.19.0

`````

**Comment by sboulema** [comment]
Thanks for reporting! Build problems should be fixed now, but the project is quite old so there may be more "surprises" ahead ;)
